version: "3.8"

services:
  cassandra:
    image: cassandra:4.1
    container_name: cassandra
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=Test Cluster
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe keyspaces'"]
      interval: 30s
      timeout: 10s
      retries: 10

  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9000:9000"
    command: server /data
    volumes:
      - minio_data:/data

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/realms/master || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 20

  edu-platform-backend:
    build:
      context: ./edu-platform-backend
      dockerfile: Dockerfile
    container_name: edu-platform-backend
    ports:
      - "8001:8000"
    depends_on:
      cassandra:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - DEBUG=True
      - CASSANDRA_CONTACT_POINTS=cassandra
      - CASSANDRA_PORT=9042
      - CASSANDRA_KEYSPACE=edu_platform
      - CASSANDRA_USERNAME=cassandra
      - CASSANDRA_PASSWORD=cassandra
      - KEYCLOAK_SERVER_URL=http://keycloak:8080
      - KEYCLOAK_REALM=edu-platform
      - KEYCLOAK_CLIENT_ID=edu-platform-backend
      - KEYCLOAK_CLIENT_SECRET=your-client-secret
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/docs || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10

  exam-service-sara-youssef:
    build:
      context: ./exam-service-sara-youssef/backend
      dockerfile: Dockerfile
    container_name: exam-service-sara-youssef
    ports:
      - "8000:8000"
    depends_on:
      edu-platform-backend:
        condition: service_healthy
      cassandra:
        condition: service_healthy
      minio:
        condition: service_started
    environment:
      - AUTH_API_URL=http://edu-platform-backend:8000
    volumes:
      - ./exam-service-sara-youssef:/app

volumes:
  cassandra_data:
  minio_data:
